### ISSUE TITLE
Another resource

### ISSUE THREAD

**Issue by spdegabrielle** [ga/awesome-geometric-algebra#3]
the first part got me interested
https://slehar.wordpress.com/2014/03/18/clifford-algebra-a-visual-introduction/ (part one)
there is also a part 2 and 3
I've since ordered a couple of books: V&GA,V&GC and GA4CS

**Comment by lukeburns** [comment]
Added!

**Comment by waldyrious** [comment]
For future reference, the addition was made in commit 1c32def5ad20e1f67004c4a09873555c93ac2f8c.
